#!/bin/bash

. ~/bin/wl_defines.sh

# TODO: Check if tree already exists first
# TODO: Bail if errors
# TODO: Log output

git_pull() {
    cd $1
    git pull
    cd ..
}

git_pull wayland
git_pull drm
git_pull mesa
git_pull libxkbcommon
git_pull pixman
git_pull cairo
git_pull libunwind
git_pull weston
